"use strict";

exports.__esModule = true;
exports.STATUS_NOT_FOUND = exports.STATUS_OK = exports.CHANGE_LOCATION = exports.CHANGE_LOADING = exports.CHANGE_STATUS = exports.RENDER_ROUTE = exports.CHANGE_ROUTE = exports.INIT_ROUTER = exports.GO_FORWARD = exports.GO_BACK = exports.GO = exports.REPLACE = exports.PUSH = exports.POP = void 0;
var POP = 'POP';
exports.POP = POP;
var PUSH = 'PUSH';
exports.PUSH = PUSH;
var REPLACE = 'REPLACE';
exports.REPLACE = REPLACE;
var GO = '@@router/GO';
exports.GO = GO;
var GO_BACK = '@@router/GO_BACK';
exports.GO_BACK = GO_BACK;
var GO_FORWARD = '@@router/GO_FORWARD';
exports.GO_FORWARD = GO_FORWARD;
var INIT_ROUTER = '@@router/INIT';
exports.INIT_ROUTER = INIT_ROUTER;
var CHANGE_ROUTE = '@@router/CHANGE_ROUTE';
exports.CHANGE_ROUTE = CHANGE_ROUTE;
var RENDER_ROUTE = '@@router/RENDER_ROUTE';
exports.RENDER_ROUTE = RENDER_ROUTE;
var CHANGE_STATUS = '@@router/CHANGE_STATUS';
exports.CHANGE_STATUS = CHANGE_STATUS;
var CHANGE_LOADING = '@@router/CHANGE_LOADING';
exports.CHANGE_LOADING = CHANGE_LOADING;
var CHANGE_LOCATION = '@@router/CHANGE_LOCATION';
exports.CHANGE_LOCATION = CHANGE_LOCATION;
var STATUS_OK = 200;
exports.STATUS_OK = STATUS_OK;
var STATUS_NOT_FOUND = 404;
exports.STATUS_NOT_FOUND = STATUS_NOT_FOUND;